# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# to run your custom scripts instead of automatic MSBuild
build_script:
  - gradlew.bat build
  - gradlew.bat test
  - gradlew.bat check

# to disable automatic tests
test: off

# to disable deployment
deploy: off
